---
title: "**Introduction (Fri.)**"
author: "Quartz Colvin (they/them)"
institute: "Rutgers University"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: ["rutgers", "rutgers-fonts"]
    lib_dir: libs
    includes:
      after_body: [nav.html, header.html]
    nature:
      ratio: "16:9"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false

---

class: center, middle

# REVIEW 

---

# Review

***???***











---

class: center, middle

# Practice

---

# Standard/Non-standard and Grammatical/Ungrammatical

In groups, invent **at least three** English sentences:

  **1.** A grammatical, standard English sentence.

  **2.** A grammatical, non-standard English sentence.

  **3.** An ungrammatical English sentence.

**Pick one** of your group’s sentences to read aloud for the rest of the class. 

The rest of the class will have to figure out which one it is.

---

class: center, middle

# Variation 

---

# Variable rules

So far we've seen that:

- **Language follows rules of a mental grammar**, much of it below the level of awareness

--

- "Grammatical" and "ungrammatical" refer to whether something is in one's mental grammar

--

- Speakers of non-standard varieties also have rules and a mental grammar

--

Another important point: **the rules of language are often variable**

- Not everyone speaks the same, and not everyone has the same mental rules.

--

- Grammar often varies by region, community, and other social factors –but no matter where you're from, you still have a mental grammar!

- This also means that what you consider grammatical/ungrammatical can vary based on what region/community you're from.

---

class: center, middle

# Practice (variable rules)

---

# Practice (variable rules)

Each one of these sentences is used (considered grammatical) in one or more varieties of American English. 

**Which of them sound natural to you? Which do not? If not, how would you say it?**

1. She was standing on line for tickets.

2. It’s a quarter of three in the afternoon.

3. I thought you might could help me.

4. Do you want to come with?

5. He doesn’t have no time.

6. I'm finished my homework.

7. My shirt needs washed.

8. He had went to the store.

*(Visit the [Yale Grammatical Diversity Project](https://ygdp.yale.edu/) for more info about each of these grammatical phenomena.)*

---

class: center, middle

# **Answers** (variable rules)

---

# Answers 

.pull-left[

1. She was standing on line for tickets.

2. It’s a quarter of three in the afternoon.

3. I thought you might could help me.

4. Do you want to come with?

5. He doesn’t have no time.

6. I'm finished my homework.

7. My shirt needs washed.

8. He had went to the store.

]

.pull-right[

1. NYC/North Jersey

2. Massachusetts

3. Southern US

4. Upper Midwest but perhaps spreading

5. Many varieties incl. African-American English

6. Philadelphia area, Canada

7. Ohio, Indiana, and surrounding area

8. Many varieties

]

---

class: center, middle

# **Linguistics as a science**

---

# Subfields of Linguistics

.pull-left[

For linguists, grammar exists on many levels of language, each of which is its own subfield of Linguistics:

- **Phonetics** – physical attributes of speech sounds

- **Phonology** – speech sounds considered as a system

- **Morphology** – structure of words

- **Syntax** – structure of sentences

- **Semantics** – literal meaning

- **Pragmatics** – implied meaning
]

.pull-right[
**Other subfields:**

- Sociolinguistics

- Linguistic Anthropology

- Historical Linguistics

- Psycholinguistics

- Neurolinguistics

- Language Acquisition

- Second Language Acquisition

- Computational Linguistics/
Natural Language Processing

- Forensic Linguistics

]

---

# Linguistics is a science

**Linguistics is the scientific study of language**

- When I say language here, I mean the human, cognitive ability to communicate through sounds/signs, not a specific language like English, Mandarin, Spanish, Arabic, etc….

--

One of the goals of linguistics is to understand speakers' mental grammars

**But what does it mean to say that it's a science? What is a science?**

---

# Linguistics as a science

Science uses the **scientific method** to test hypotheses about how natural phenomena (in our case, language) work:

1. Develop a **hypothesis** grounded in personal observations, theory, and previous research.

--

2. **Design an experiment** to collect real-world (empirical) data to test your hypothesis.

--

3. Run your experiment, **collect your data**.

--

4. **Analyze** your data – is your hypothesis true or false?

--

5. Based on your results, **update your theories**, develop a new hypothesis, and **repeat**!


---

class: center, middle

# Practice (Linguistics as a science)

---

# Practice (linguistics uses the scientific method)

**Come up with your own experiment:**

- Most English permits only 1 modal/clause:

  *I might eat. I could eat.*

- Southern American English permits 2:

  *I might could eat.*

--

**1.** Come up with a **hypothesis** – a statement that could be true or false – about English modals.

- *(Ideas: Where specifically? What about other modals: can, may, should, oughta? Does anyone use more than 2?)*

**2.** What kind of data could you collect to prove or disprove your hypothesis? 

**3.** How could you design an experiment to collect that data?

---

class: center, middle

# Summary

---

# **Summary**

- Language follows rules of a **mental grammar**

- All speakers of all languages have a mental grammar

--

  - **Grammatical/ungrammatical** refers to whether a construction is in your mental grammar

--

  - **Non-standard varieties** also have rules and a mental grammar
  
  - The exact rules/mental grammar of a language varies by place and community

--

- **Grammar exists on multiple levels**, and each of these levels is a subfield of Linguistics

--

- **Linguistics is a science**. it uses empirical data and the scientific method to test hypotheses about how a natural phenomenon (language) works






---

# Coming up

### Reading

- Read *Anderson, Ch1*, if you haven't yet!


