---
title: "**Syntax**"
subtitle: "**Friday Materials**"
author: "Quartz Colvin (they/them)"
institute: "Rutgers University"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: ["rutgers", "rutgers-fonts"]
    lib_dir: libs
    includes:
      after_body: [nav.html, header.html]
    nature:
      ratio: "16:9"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false

---


class: middle, center 

# Constituents!

---

# Constituents 

## What is a constituent? 

- ***A group of words that acts together as a unit***

- a basic structure in syntax

--

Some examples

- **Justin** teaches linguistics.

- **My cat** likes rice.

- **That tall guy from NJ** likes philosophy.

--

Even though the bold constituents can have only one word or several, they act as a unit to describe a single concept.

---

# Constituents: phrases (types)

**Phrases** are types of constituents 

--

Each phrase has a main word (or **head**), and phrases are named after the head word's part of speech.

---

# Constituents: phrases

- Noun phrase (NP)
  
  - *woman, the woman, the happy woman, the woman with the hat*
  
- Prepositional phrase (PP)

  - *into the forest, by the author, for good luck*

- Verb phrase (VP)

  - *eats, eats pizza, eats quickly, eats pizza quickly at midnight*
  
- Adjective phrase (AdjP)

  - *happy*
  
- Adverb phrase (AdvP)

  - *quickly*

**Note that one constituent may contain another, smaller constituent.**

---

class: center, middle

# Constituency tests!

---

# Constituency tests 
We can do tests to determine whether a group of words form a constituent or not.

These are the four tests we'll use:

--

1. replacement/substitution 

2. stand-alone

3. movement 

4. coordination 

**As is usually the case, these tests don't always work 100% of the time, so you should try multiple!!!**

---

# Constituency tests 

Consider the following sentence ([the happy student] and [in New Brunswick] are constituents)

- [The happy student] lives [in New Brunswick]

This is the example sentence which we will perform constituency tests for.

---

# Constituency tests

## Replacement


**Replacement test:** try replacing a group of words with a *pro-form* (a pronoun or another generic expression such as *there, like that, do, do that, that way*).

If it works, or still sounds grammatical, then the words are a constituent.

--

- [The happy student] lives in New Brunswick → [She] lives in New Brunswick
  
  - this works, so [the happy student] is a constituent!

--

- The happy student [lives in New] Brunswick → The happy student [??] Brunswick

  - this **doesn't** work, so [lives in New] is not a constituent 


---

# Constituency tests 

## Stand alone

**Stand alone test:** try coming up with a question that can be answered by just saying the group of words you want to test on its own

- Who lives in New Brunswick? [The happy student]!

  - this works, so [the happy student] is a constituent


---

# Constituency tests  

## Movement 

**Movement test:** try moving a group of words to a different part of the sentence, like the beginning or end of the sentence. You *may* need to add extra words to support this movement.

- The person who lives in New Brunswick is [the happy student].

  - this works, so [the happy student] is a constituent
  
- Student who lives in New Brunswick is [the happy]

  - this doesn't work, so [the happy] is not a constituent


---

# Constituency tests 

## Coordination 

**Coordination test:** coordinating conjunctions like *and* or *or* will always join two words or phrases of the same type. So, if a group of words is a constituent, you should be able to insert another phrase of the same type joined with *and* or *or*

- [The happy student] and [the grumpy professor] live in New Brunswick.

  - this works, so [the happy student] is a constituent

class: middle, center

# Syntax trees!

---

# PSR rules

**Tips:**

- pay attention to what modifies what! if X modifies Y, X must be a child of the same *parent* as Y (X and Y are *sisters*)

--

TP → NP (T) VP

NP → (D) (AdjP+) N (PP+)

NP → N

PP → P NP

VP → (AdvP+) V (NP) (AdvP+) (PP+) (AdvP+)

AdjP → (AdvP) Adj

AdvP → (AdvP) Adv

---

class: middle, center

# Practice: phrases

---

# Phrases practice

Draw mini-trees for the phrases in red in the following sentences.

--

1. I ate **an apple.** 

2. Don't stare at **the bright sun.**

3. John went **into the building.**

4. They're like **peas in a pod.**

5. The bakery sells **wonderfully fresh bread.**

6. I like to drive **really slowly.**

7. I threw a ball to **the dog with the collar in the park.**

8. The mechanic helped **the man in the car with the flat tire.**

---

class: middle, center

# Practice: sentences

---

# Practice: sentences

Draw trees for the following sentences. 

--

1. The robin caught a worm.

2. The mockingbird was singing.

3. The sparrow on the windowsill chirped loudly.

4. The osprey brought its hungry chicks a fish.

5. The large owl lives in a nest in the barn.

6. The duck quickly led her ducklings across the street.

---

# Practice: complex sentences (if time!)

Identify the dependent clause and complementizer (if any) in each of these sentences, and determine whether the CP is acting as an NP, AdvP, or AdjP, and whether it is being inserted into an NP or a VP.

--

1. John said that he likes pizza.

2. I want to go to California.

3. I saw a deer that was grazing in the park. 
