---
title: "**Phonetics**"
subtitle: "**ANSWERS**"
author: "Quartz Colvin (they/them)"
institute: "Rutgers University"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: ["rutgers", "rutgers-fonts"]
    lib_dir: libs
    includes:
      after_body: [nav.html, header.html]
    nature:
      ratio: "16:9"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false

---

# Identifying vowels

**(1) Identify which vowels are in the following words, (2) give the IPA symbol for them, and (3) define them using the big three features.**

1. cat **[æ]**

2. thrift **[ɪ]**

3. red **[ɛ]**

4. reed **[i]**

5. hard **[ɑ]**

6. boot **[u]**

7. cut **[ʌ]**

8. pet **[ɛ]**

9. pot **[ɑ] or [ɔ]**

10. fork **[o]**


---

# Transcription practice

**Transcribe the same words into IPA.**

1. cat 

2. thrift

3. red

4. reed

5. hard

6. boot

7. cut

8. pet

9. pot 

10. fork

---

# Transcription practice

**What English words do these IPA transcriptions correspond to?**

1. [ˈkæ.lən.dɹ] **calendar**

2. [ˈbɹɪŋ.ɪŋ] **bringing**

3. [ˈtɛl.ə.ˌvɪʒ.n] **television**

4. [ˈðiz] **these**

5. [ˈθɪŋk] **think**

6. [ˈʃæk] **shack**

7. [ˈnʌ.θɪŋ] **nothing**

8. [ˈplʌk] **pluck**

9. [mejk] **make**

10. [klawdz] **clouds**

---

# More complex words

**Transcribe into IPA.**

1. water

2. orange

3. extremely

4. portrays

5. successful

6. noises

7. poor

8. technology

9. philosopher

10. handkerchiefs

---

# More complex words

**What English words do these IPA transcriptions correspond to?**

1. [ˈelbəw]

2. [vajəˈlɪn]

3. [ˈajlənd]

4. [ˈpiːpl]

5. [ˈdʒʌmpər]

6. [ˈdendʒərəs]

7. [ˈiːzi]

8. [jʌŋ]

9. [ɡreps]

10. [rajs]

---

# More complex words

**What English words do these IPA transcriptions correspond to?**

1. [ˈbɑːθruːm]

2. [ˈʌŋkl]

3. [ˈrʌbər]

4. [rajt]

5. [ˈejrpɔrt]

6. [ɔːˈɡʌst]

7. [jɪr]

8. [ɡəˈrɪlə]

9. [ˈbʌtərflaj]

10. [məˈskiːtəw]

---

# Practice (description)

**Give a full description of EACH consonant in the following words, and give the corresponding IPA symbol.** (Ex. [p] *is a voiceless bilabial stop*)

1. move

  - **[m]: voiced bilabial nasal**
  
  - **[v]: voiced labiodental fricative**

2. hide

  - **[h]: voiceless glottal fricative**
  
  - **[d]: voiced post-alveolar plosive**

3. cloth

  - **[k]: voiceless velar plosive**
  
  - **[l]: voiced lateral velar approximant**
  
  - **[θ]: voiceless dental fricative**
  
---

# Practice (description)

**Give a full description of EACH consonant in the following words, and give the corresponding IPA symbol.**

4. stove

  - **[s]: voiceless alveolar fricative**
  
  - **[t]: voiceless dental plosive**
  
  - **[v]: voiced labiodental fricative**

5. gosh

  - **[g]: voiced velar plosive**
  
  - **[ʃ]: voiceless post-alveolar fricative**
  
---

# Practice (description)

**Give a full description of EACH consonant in the following words, and give the corresponding IPA symbol.**

6. bank

  - **[b]: voiced bilabial plosive**
  
  - **[n]: voiced alveolar nasal**
  
  - OR **[ŋ]: voiced velar nasal**

  - **[k]: voiceless velar plosive**
  
---

# Practice (description)

**Give a full description of EACH consonant in the following words, and give the corresponding IPA symbol.**
  
7. thrift

  - **[θ]: voiceless dental fricative**
  
  - **[ɹ]: voiced alveolar approximant**
  
  - **[f]: voiceless labiodental fricative**
  
  - **[t]: voiceless alveolar plosive**

8. hard

  - **[h]: voiceless glottal fricative**
  
  - **[ɹ]: voiced alveolar approximant**
  
  - **[d]: voiced alveolar plosive**
  
---
  
# Practice (description)

**Give a full description of EACH consonant in the following words, and give the corresponding IPA symbol.**

9. fork

  - **[f]: voiceless labiodental fricative**
  
  - **[ɹ]: voiced alveolar approximant**
  
  - **[k]: voiceless velar plosive**

---

# Practice (description)

**Give the full description of each IPA symbol, and give an example of an English word with that phoneme in it.**

1. [f] **voiceless **

2. [l] **voiced lateral velar approximant**

3. [ŋ] **voiced velar nasal**

4. [k] **voiceless velar plosive**

5. [ʔ] **voiceless glottal plosive**

6. [w] **voiced labial-velar approximant**

7. [ð] **voiced dental fricative**

8. [t͡ʃ] **voiceless palato-alveolar affricate**

9. [θ] **voiceless dental fricative**






